### ISSUE TITLE
forward controllers should wait for a signal from the hardware to finish

### ISSUE THREAD

**Issue by fmauch** [fzi-forschungszentrum-informatik/cartesian_ros_control#17]
Currently, the passthrough controllers send the trajectory and when the designated time is up, it is checked whether the robot is at its final position or not (within specified limits).

I think that we should not use such a fire&forget&check interface but rather wait for the underlying hardware to signal completion.

E.g. for the `ur_robot_driver` we should send something back when reaching [this line](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/blob/beta-testing/ur_robot_driver/resources/ros_control.urscript#L153).

As this will introduce a potential endless wait, we should implement a strategy to either read keepalive signals from the hardware or add a user-specified timeout that we can use ontop of the trajectory time to declare a goal `LOST´.

**Comment by stefanscherzinger** [comment]
I personally think that

>  either read keepalive signals from the hardware 

Is a bit against our rational _to not behave_ as a controller but stay as light-weight as possible and that

> user-specified timeout that we can use ontop of the trajectory time to declare a goal `LOST´.

sounds like more complexity that bloats our trajectory definition. It should have exactly the specified time to execute. If that succeeds, great. If it fails, then it fails.

> I think that we should not use such a fire&forget&check interface

Why would you change this @fmauch? The notification is implicitly given with the tolerance checks.

**Comment by fmauch** [comment]
> Why would you change this @fmauch? The notification is implicitly given with the tolerance checks.

No, it is not. In the controller we check the error currently reported by the hardware. In case of the `ur_robot_driver` that's the difference between the targeted joint positions (as in the input for the internal robot controller) and the actual joint positions. Given that the robot controller behaves correctly, this error will *always* be very small. When the time is up, you check whether that error is small and if it is, you return succeeded. This does not say anything about whether the actual goal was reached or not.

> sounds like more complexity that bloats our trajectory definition. It should have exactly the specified time to execute. If that succeeds, great. If it fails, then it fails.

Whether the trajectory finishes in time or not is up to the ROS controller to check. Whether the trajectory finished or not in my opinion should be signaled by the part that is actually executing the trajectory, which is the robot controller. I don't think, that this is some kind of complexity, but the necessary steps that I would have expected to be taken.

**Comment by stefanscherzinger** [comment]
> difference between the targeted joint positions (as in the input for the internal robot controller) and the actual joint positions

Maybe I'm misunderstanding, but aren't the targeted joint positions exactly what comes out of the forwarding controller? If the robot does in fact manage to drive to these positions and reports its error, isn't that what we are interested in for checking success? Do you believe there's reason to mistrust the driver's error?

> Whether the trajectory finished or not in my opinion should be signaled by the part that is actually executing the trajectory, which is the robot controller

I'm not completely sure but I thought that the JointTrajectoryController e.g. stops when the given time is up and checks the tolerances and that the ROS-Control concept of read()/write() cycles does not envision such _additional notifications_. The controllers have the task to make informed decisions on the feedback they get back in read(). I would expect the forwarding controllers to behave similar and let them take care of time keeping and feedback checking.

**Comment by fmauch** [comment]
> > difference between the targeted joint positions (as in the input for the internal robot controller) and the actual joint positions
> 
> Maybe I'm misunderstanding, but aren't the targeted joint positions exactly what comes out of the forwarding controller? If the robot does in fact manage to drive to these positions and reports its error, isn't that what we are interested in for checking success? Do you believe there's reason to mistrust the driver's error?

It's not about mistrust. But the error reported from that will always be `~0` at **any** time of execution, (probably even if the robot is standing due to a protective stop). So, if we *think* that the motion is done and check this error, we will always report a successful motion no matter whether the motion actually succeeded or was even taking place.

> I'm not completely sure but I thought that the JointTrajectoryController e.g. stops when the given time is up and checks the tolerances and that the ROS-Control concept of read()/write() cycles does not envision such additional notifications. The controllers have the task to make informed decisions on the feedback they get back in read(). I would expect the forwarding controllers to behave similar and let them take care of time keeping and feedback checking.

Which is why I tried to explain my view of the difference of the *executing* part and the ROS controller running ontop. In case of the traditional JointTrajectoryController the ROS controller is both, though it is only feed-forwarding joint positions in the position case. However, the ROS controller checks the tolerances in that case. If the robot doesn't move according to the commands we sent it, that will show up as an error. With the implementation of *this* controller, we tell the robot "do something and as long as you tell me everything is fine, I'm fine. After a while I will simply decide that we're done and everything is fine.". As we are forwarding trajectory execution to the robot, we should also let the robot take care of time tracking status reporting. I am aware, that this cannot (and should not) be done similar to the JointTrajectoryController, but whether the execution is finished or not should be (IMHO) up to the robot controller to decide.
