### ISSUE TITLE
[forward_controllers] Using tolerances lead to assertion_error if RobotHW doesn't provide a full tolerance

### ISSUE THREAD

**Issue by fmauch** [fzi-forschungszentrum-informatik/cartesian_ros_control#18]
When using tolerances with the passthrough controllers, the controller crashes with an assertion_error if the RobotHW doesn't provide a full error state including accelerations and efforts.

e.g. when using with the current implementation inside the `ur_robot_driver` the joint error looks like this:

```
positions[]
  positions[0]: 0
  positions[1]: 0
  positions[2]: 0
  positions[3]: 0
  positions[4]: 0
  positions[5]: 0
velocities[]
  velocities[0]: 0
  velocities[1]: 0
  velocities[2]: 0
  velocities[3]: 0
  velocities[4]: 0
  velocities[5]: 0
accelerations[]
effort[]
```

That they are all exactly 0 seems a bit suspicious, but that's a separate topic. However, that `accelerations` and `effort` are empty leads to the mentioned assertion_error from https://github.com/fzi-forschungszentrum-informatik/cartesian_ros_control/blob/0a908ce355e13b16f55b4633623f32c9d3906240/pass_through_controllers/include/pass_through_controllers/pass_through_controllers.hpp#L249-L251

Is that on purpose and the implementation in `ur_robot_driver` should be changed and if so, why is acceleration required, but not effort? This seems a bit arbitrary to me.

---
**Edit:** They are all 0 as I am using URSim for testing, where target == actual.

**Comment by stefanscherzinger** [comment]
> Is that on purpose and the implementation in ur_robot_driver should be changed and if so, why is acceleration required, but not effort? This seems a bit arbitrary to me.

I remember that the purpose was rather to test for consistency by checking their sizes. I understand that the pass_through_controllers should be more permissive if the drivers do not provide the _full_ set of error_tolerances.

> This seems a bit arbitrary to me.

You are right. I'll change this to an optional check for each error field and check for the correct size only when they are not zero.

**Comment by stefanscherzinger** [comment]
@fmauch: Note that [control_msgs::JointTolerance](http://docs.ros.org/en/noetic/api/control_msgs/html/msg/JointTolerance.html) does not provide a tolerance for effort.
