### ISSUE TITLE
[Question] Speed scale trajectories available for UR 10e?

### ISSUE THREAD

**Issue by DanielSchimpf** [fzi-forschungszentrum-informatik/cartesian_ros_control#3]
Hello,

I am considering using this controller because I would like to send a trajectory to the UR 10e and then change the speed during the execution from a ROS node. 

I saw that you say that "Speed-scale trajectories" is available to "Robots with new interfaces". Does the UR 10e fall under that category? How can I check if the UR 10e does? (My system is Ubuntu 16 with kinetic. Don't know if the driver makes a difference, but I am currently using this one: https://github.com/UniversalRobots/Universal_Robots_ROS_Driver)

A more general question, because I have mostly used moveit so far: How do I best get started with the cartesian_ros_control?

Thanks!

Daniel

**Comment by stefanscherzinger** [comment]
Hi @DanielSchimpf ,

Yes, this feature is available on the [beta-testing](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/tree/beta-testing) branch of the driver. You also need the beta-testing-boost branch of the [client library](https://github.com/UniversalRobots/Universal_Robots_Client_Library/tree/beta-testing-boost). Are you familiar with ROS control yet?

**Comment by fmauch** [comment]
As this repository will be archived soon in favor of a couple of new ones (Notice about that coming soon) and the scaling has been addressed in #21 I will go ahead and close this issue.
