### ISSUE TITLE
foward_joint_traj_controller does not take into account sequence of joints defined in trajectory #beta-testing

### ISSUE THREAD

**Issue by janisa9** [fzi-forschungszentrum-informatik/cartesian_ros_control#4]
After setting up and testing pass_through controllers we experienced some weird behaviour through MoveIt and also while executing our prerecorded trajectory. The issue is that the sequence of the joints which is defined in the trajectory is not taken into account. The sequence of joint names in our prerecorded trajectory was following: elbow_joint, shoulder_pan_joint, shoulder_lift_joint, wrist1, wrist2, wrist3 and the values of positions in respective order. 

It seems that the controller takes the first value assuming that it is the shoulder_pan_joint, but in reality, in this case, this was elbow_joint. And this of course explained the weird behaviour.

After manually modifying position values so that the shoulder_pan_joint comes first, the trajectory was executed correctly. We also tried the same setup with scaled_pos_joint_traj_controller, where joint names are taken into account.

**Comment by stefanscherzinger** [comment]
Thanks @janisa9 for reporting this! We'll have a look.

**Comment by stefanscherzinger** [comment]
@janisa9 A possible fix is implemented [here](https://github.com/UniversalRobots/Universal_Robots_ROS_Driver/pull/345).

**Comment by janisa9** [comment]
@stefanscherzinger Thank you, yes this solves the issue. I will proceed with further testing to see how the controller is working.
